# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - "/src"

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: "<azure dev ops registry connection>"
  containerRegistry: "<your azure container registry>.azurecr.io"
  imageRepository: "<your image repository>"
  dockerfilePath: "$(Build.SourcesDirectory)/Dockerfile"
  tag: "latest"

  # Agent VM image name
  vmImageName: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build and push streamlit app
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          # build docker image
          - task: Docker@2
            displayName: Build Streamlit Docker Image
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
