# copy this file, rename it as secrets.toml and fill snowflake connexion infos
[snowflake]
account = "xxx"
warehouse = "xxx"
database = "xxx"
user = "xxx""
password = "xxx"
role = "xxx"
database = "xxx"
